-- +goose Up
-- +goose StatementBegin
CREATE TABLE CHAT_ROOMS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE CHAT_ROOMS;
-- +goose StatementEnd
