version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=jobsity
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - RMQ_HOST=rabbitmq
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - RMQ_PORT=5672
      - JWT_TTL=60
      - JWT_SECRET=secret
      - JWT_ISSUER=jobsity
    depends_on:
      - db
      - rabbitmq
    entrypoint: /app/entrypoint.sh 
    ports:
      - "8080:8080"
  db:
    image: postgres:11.10
    environment:
      POSTGRES_DB: jobsity
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
