// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	zerolog "github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields:
func (_m *Logger) Debug() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// Err provides a mock function with given fields: err
func (_m *Logger) Err(err error) *zerolog.Event {
	ret := _m.Called(err)

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func(error) *zerolog.Event); ok {
		r0 = rf(err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *Logger) Error() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// Fatal provides a mock function with given fields:
func (_m *Logger) Fatal() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// Info provides a mock function with given fields:
func (_m *Logger) Info() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// Level provides a mock function with given fields:
func (_m *Logger) Level() zerolog.Level {
	ret := _m.Called()

	var r0 zerolog.Level
	if rf, ok := ret.Get(0).(func() zerolog.Level); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(zerolog.Level)
	}

	return r0
}

// Log provides a mock function with given fields:
func (_m *Logger) Log() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// Panic provides a mock function with given fields:
func (_m *Logger) Panic() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// SetGlobalLevel provides a mock function with given fields: level
func (_m *Logger) SetGlobalLevel(level zerolog.Level) {
	_m.Called(level)
}

// SetLevel provides a mock function with given fields: level
func (_m *Logger) SetLevel(level zerolog.Level) {
	_m.Called(level)
}

// Trace provides a mock function with given fields:
func (_m *Logger) Trace() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// Warn provides a mock function with given fields:
func (_m *Logger) Warn() *zerolog.Event {
	ret := _m.Called()

	var r0 *zerolog.Event
	if rf, ok := ret.Get(0).(func() *zerolog.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Event)
		}
	}

	return r0
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
